version: '4.2'
services:
  mongo:
    image: mongo
    container_name: microservicio_monopatin
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
